force-app/main/default/objects/Assessment_Question_Setting__mdt/Assessment_Question_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Stores configuration settings for specific assessment questions</description>
    <label>Assessment Question Setting</label>
    <pluralLabel>Assessment Question Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Assessment_Question_Setting__mdt/fields/Criteria_Value__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Value__c</fullName>
    <label>Criteria Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Question_Setting__mdt/fields/Driven_Question_Name__c.field-meta.xml
<CustomField>
    <fullName>Driven_Question_Name__c</fullName>
    <inlineHelpText>A question behavior that is driven by the driving question</inlineHelpText>
    <label>Driven Question Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Question_Setting__mdt/fields/Driving_Question_Name__c.field-meta.xml
<CustomField>
    <fullName>Driving_Question_Name__c</fullName>
    <inlineHelpText>A question that is driving behavior of other questions</inlineHelpText>
    <label>Driving Question Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Question_Setting__mdt/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <description>denotes the purpose of the setting</description>
    <label>Purpose</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NA Criteria</fullName>
                <default>true</default>
                <label>NA Criteria</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssessmentQuestionSetting.cls
public virtual class AssessmentQuestionSetting {
    public static final String PURPOSE_NA_CRITERIA = 'NA Criteria';

    private static AssessmentQuestionSetting setting;

    @TestVisible
    private Map<String, List<Assessment_Question_Setting__mdt>> settingsCache;

    private AssessmentQuestionSetting() {
        this.settingsCache = new Map<String, List<Assessment_Question_Setting__mdt>>();
    }

    public static AssessmentQuestionSetting getInstance() {
        if(setting == null) {
            setting = new AssessmentQuestionSetting();
        } 

        return setting;
    }

    /**
     * @description getNaValuesSettings description
     * @return   Map<DrivenQuestion, Map<DrivingQuestion, CriteriaValue>>
     */ 
    public Map<String, Map<String, String>> getNaValuesSettings() {
        if(!settingsCache.containsKey(PURPOSE_NA_CRITERIA)) {
           settingsCache.put(PURPOSE_NA_CRITERIA, [SELECT Driving_Question_Name__c, Driven_Question_Name__c, Criteria_Value__c FROM Assessment_Question_Setting__mdt WHERE Purpose__c = :PURPOSE_NA_CRITERIA]);
        }
        List<Assessment_Question_Setting__mdt> settings = settingsCache.get(PURPOSE_NA_CRITERIA);
        
        Map<String, Map<String, String>> result = new Map<String, Map<String, String>>();
        for(Assessment_Question_Setting__mdt setting : settings) {
            if(!result.containsKey(setting.Driven_Question_Name__c)) {
                result.put(setting.Driven_Question_Name__c, new Map<String, String>());
            }
            result.get(setting.Driven_Question_Name__c).put(setting.Driving_Question_Name__c, setting.Criteria_Value__c);
        }

        return result;
    }


}